# Generated by Django 5.1.2 on 2025-05-28 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_audio_duration', models.PositiveIntegerField(default=3600, help_text='用户剩余可用的音频制作时长，单位为秒', verbose_name='剩余音频时长(秒)')),
                ('available_storage_bytes', models.PositiveBigIntegerField(default=1073741824, help_text='用户可用的存储空间大小，单位为字节', verbose_name='可用存储空间(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户配额',
                'verbose_name_plural': '用户配额',
            },
        ),
    ]
