# Generated by Django 5.1.2 on 2025-05-28 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('audio_create', '音频创建'), ('audio_delete', '音频删除'), ('file_upload', '文件上传'), ('file_delete', '文件删除'), ('quota_consume', '配额消耗'), ('quota_add', '配额增加'), ('user_login', '用户登录'), ('user_logout', '用户登出'), ('system_operation', '系统操作'), ('other', '其他操作')], help_text='操作的类型分类', max_length=50, verbose_name='操作类型')),
                ('operation_object', models.CharField(blank=True, help_text='操作的目标对象，如文件名、音频ID等', max_length=200, null=True, verbose_name='操作对象')),
                ('operation_detail', models.TextField(blank=True, help_text='操作的详细描述信息', null=True, verbose_name='详细描述')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('pending', '进行中'), ('cancelled', '已取消')], default='success', max_length=20, verbose_name='操作状态')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='操作相关的额外信息，如文件大小、音频时长等', verbose_name='元数据')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='操作时的IP地址', null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, help_text='操作时的浏览器信息', null=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(help_text='执行操作的用户', on_delete=django.db.models.deletion.CASCADE, related_name='operation_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='home_operat_user_id_c37722_idx'), models.Index(fields=['operation_type', '-created_at'], name='home_operat_operati_e07e89_idx'), models.Index(fields=['status', '-created_at'], name='home_operat_status_37aaa9_idx')],
            },
        ),
    ]
