# Generated by Django 5.1.2 on 2025-09-04 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userquota_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('audio_generation', '音频生成'), ('ocr_processing', 'OCR处理')], help_text='选择要配置的操作类型', max_length=50, unique=True, verbose_name='操作类型')),
                ('points_per_unit', models.IntegerField(default=0, help_text='每个单位操作需要的积分数', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='每单位积分')),
                ('unit_name', models.CharField(default='次', help_text='计费单位名称，如：秒、页、次等', max_length=50, verbose_name='单位名称')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此积分规则', verbose_name='是否启用')),
                ('description', models.TextField(blank=True, help_text='对此积分规则的详细描述', verbose_name='规则描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '积分配置',
                'verbose_name_plural': '积分配置',
                'ordering': ['operation_type'],
            },
        ),
    ]
