# Generated by Django 5.1.2 on 2025-09-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pointsconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquota',
            name='available_storage_bytes',
        ),
        migrations.RemoveField(
            model_name='userquota',
            name='remaining_audio_duration',
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='operation_type',
            field=models.CharField(choices=[('audio_create', '音频创建'), ('audio_delete', '音频删除'), ('file_upload', '文件上传'), ('file_delete', '文件删除'), ('quota_consume', '配额消耗'), ('quota_add', '配额增加'), ('user_login', '用户登录'), ('user_logout', '用户登出'), ('system_operation', '系统操作'), ('other', '其他操作')], help_text='操作的类型分类', max_length=50, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='points',
            field=models.PositiveIntegerField(default=1000, help_text='用户可用于音频生成和OCR处理的积分', verbose_name='用户积分'),
        ),
    ]
