# Generated by Django 5.1.2 on 2025-10-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_old_quota_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_ads_enabled', models.BooleanField(default=False, help_text='是否在网站中启用 Google Ads 脚本', verbose_name='启用 Google Ads')),
                ('google_ads_script', models.TextField(blank=True, help_text='Google Ads 的 JavaScript 脚本代码', verbose_name='Google Ads 脚本')),
                ('ads_txt_content', models.TextField(blank=True, help_text='ads.txt 文件的内容，用于广告验证', verbose_name='ads.txt 内容')),
                ('site_description', models.TextField(blank=True, help_text='站点的 meta description，用于 SEO', verbose_name='站点描述')),
                ('site_keywords', models.TextField(blank=True, help_text='站点的 meta keywords，用于 SEO', verbose_name='站点关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
        migrations.AlterField(
            model_name='pointsconfig',
            name='operation_type',
            field=models.CharField(choices=[('audio_generation', '音频生成'), ('ocr_processing', 'OCR处理'), ('llm_usage', 'LLM调用')], help_text='选择要配置的操作类型', max_length=50, unique=True, verbose_name='操作类型'),
        ),
    ]
