# Generated by Django 5.1.2 on 2025-10-08 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0006_siteconfig_alter_pointsconfig_operation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='留言的具体内容', verbose_name='留言内容')),
                ('object_id', models.PositiveIntegerField(help_text='留言关联的对象ID', verbose_name='关联对象ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(help_text='发表留言的用户', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='留言者')),
                ('content_type', models.ForeignKey(help_text='留言关联的模型类型', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联模型')),
                ('parent', models.ForeignKey(blank=True, help_text='如果是回复留言，则指向被回复的留言', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.comment', verbose_name='父级留言')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-created_at'], name='home_commen_content_bbe3a9_idx'), models.Index(fields=['author', '-created_at'], name='home_commen_author__9352c0_idx'), models.Index(fields=['parent', '-created_at'], name='home_commen_parent__049f19_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='讨论主题的标题', max_length=200, verbose_name='主题标题')),
                ('content', models.TextField(help_text='主题的详细描述和内容', verbose_name='主题内容')),
                ('category', models.CharField(choices=[('general', '综合讨论'), ('technical', '技术交流'), ('feedback', '反馈建议'), ('help', '求助问答'), ('announcement', '公告通知'), ('other', '其他话题')], default='general', help_text='选择主题的分类', max_length=20, verbose_name='主题分类')),
                ('is_pinned', models.BooleanField(default=False, help_text='是否将此主题置顶显示', verbose_name='是否置顶')),
                ('is_closed', models.BooleanField(default=False, help_text='是否关闭此主题，关闭后不能回复', verbose_name='是否关闭')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='主题被查看的次数', verbose_name='查看次数')),
                ('reply_count', models.PositiveIntegerField(default=0, help_text='主题下的回复数量', verbose_name='回复数量')),
                ('last_reply_at', models.DateTimeField(blank=True, help_text='最后一条回复的时间', null=True, verbose_name='最后回复时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(help_text='创建此主题的用户', on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topics', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '讨论主题',
                'verbose_name_plural': '讨论主题',
                'ordering': ['-is_pinned', '-last_reply_at', '-created_at'],
                'indexes': [models.Index(fields=['category', '-created_at'], name='home_discus_categor_43f774_idx'), models.Index(fields=['author', '-created_at'], name='home_discus_author__ac7d08_idx'), models.Index(fields=['is_pinned', '-created_at'], name='home_discus_is_pinn_4fb60e_idx'), models.Index(fields=['-last_reply_at'], name='home_discus_last_re_d212c3_idx')],
            },
        ),
    ]
