# Generated by Django 5.1.2 on 2025-10-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comment_discussiontopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='s3_access_key_id',
            field=models.CharField(blank=True, help_text='S3 访问密钥 ID', max_length=255, verbose_name='S3 Access Key ID'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='s3_bucket_name',
            field=models.CharField(blank=True, help_text='S3 存储桶名称', max_length=255, verbose_name='S3 存储桶名称'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='s3_custom_domain',
            field=models.CharField(blank=True, help_text='S3 自定义域名（用于CDN加速）', max_length=255, verbose_name='S3 自定义域名'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='s3_enabled',
            field=models.BooleanField(default=False, help_text='是否启用 S3 对象存储（启用后文件将上传到S3）', verbose_name='启用 S3 对象存储'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='s3_endpoint_url',
            field=models.CharField(blank=True, help_text='S3 兼容服务的端点URL（如使用其他S3兼容服务）', max_length=255, verbose_name='S3 端点URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='s3_prefix',
            field=models.CharField(blank=True, default='media/', help_text='S3 存储路径前缀', max_length=100, verbose_name='S3 路径前缀'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='s3_region',
            field=models.CharField(blank=True, default='us-east-1', help_text='S3 存储区域（如：us-east-1, cn-north-1）', max_length=50, verbose_name='S3 区域'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='s3_secret_access_key',
            field=models.CharField(blank=True, help_text='S3 秘密访问密钥', max_length=255, verbose_name='S3 Secret Access Key'),
        ),
    ]
