# Generated by Django 5.1.2 on 2024-11-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workbench", "0002_books_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="file_type",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="books",
            name="name",
            field=models.TextField(default=""),
        ),
    ]
