# Generated by Django 5.1.2 on 2025-02-07 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0003_books_file_type_books_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(default='admin')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('book_page', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='audio_segments/%Y/%m/%d/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_segments', to='workbench.books')),
            ],
        ),
    ]
