# Generated by Django 5.1.2 on 2025-04-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0004_audiosegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosegment',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
