# Generated by Django 5.1.2 on 2025-04-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0005_audiosegment_published'),
        ('workbench', 'assign_to_superuser'),
    ]

    operations = [
    ]
