# Generated by Django 5.1.2 on 2025-04-17 05:05

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0008_assign_data_to_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='books',
            name='updated_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='audiosegment',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='audiosegment',
            name='updated_at',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
