# Generated by Django 5.1.2 on 2025-07-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0013_books_md5_hash'),
        ('workbench', '0014_calculate_existing_books_md5'),
    ]

    operations = [
    ]
