# Generated by Django 5.1.2 on 2025-07-08 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0015_merge_20250708_1455'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='对话脚本标题', max_length=500)),
                ('original_text', models.TextField(help_text='原始文本内容')),
                ('script_data', models.JSONField(help_text='LLM解析后的JSON格式对话数据')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='dialogue_audio/%Y/%m/%d/')),
                ('audio_duration', models.FloatField(blank=True, help_text='音频时长（秒）', null=True)),
                ('published', models.BooleanField(default=False, help_text='是否发布到成品')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_scripts', to='workbench.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='角色名称，如：主持人、嘉宾、旁白等', max_length=100)),
                ('tts_provider', models.CharField(choices=[('edge_tts', 'Edge TTS'), ('azure', 'Azure TTS')], default='azure', max_length=20)),
                ('voice_name', models.CharField(help_text='TTS语音模型名称', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认角色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DialogueSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(help_text='说话者名称', max_length=100)),
                ('sequence', models.IntegerField(help_text='片段顺序')),
                ('utterance', models.TextField(help_text='说话内容')),
                ('dialogue_type', models.CharField(choices=[('dialogue', '对话'), ('narration', '旁白')], default='dialogue', max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='dialogue_segments/%Y/%m/%d/')),
                ('audio_duration', models.FloatField(blank=True, help_text='片段音频时长（秒）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='workbench.dialoguescript')),
                ('voice_role', models.ForeignKey(blank=True, help_text='分配的音色角色', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workbench.voicerole')),
            ],
            options={
                'ordering': ['script', 'sequence'],
                'unique_together': {('script', 'sequence')},
            },
        ),
    ]
