# Generated by Django 5.1.2 on 2025-08-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0016_dialoguescript_voicerole_dialoguesegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosegment',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/audio_segments/%Y/%m/%d/', verbose_name='字幕文件'),
        ),
        migrations.AddField(
            model_name='dialoguescript',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/dialogue_scripts/%Y/%m/%d/', verbose_name='字幕文件'),
        ),
    ]
