# Generated by Django 5.1.2 on 2025-09-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0017_audiosegment_subtitle_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_md5', models.CharField(db_index=True, help_text='图片的MD5哈希值', max_length=32, unique=True)),
                ('ocr_text', models.TextField(help_text='OCR识别的文本内容')),
                ('source_type', models.CharField(choices=[('page_image', '页面图片'), ('manual_upload', '手动上传')], default='page_image', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
