# Generated by Django 5.1.2 on 2025-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0018_ocrcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pdf_type',
            field=models.CharField(choices=[('unknown', '未检测'), ('text', '文本版'), ('scanned', '扫描版')], default='unknown', help_text='PDF类型：文本版或扫描版', max_length=20),
        ),
    ]
