# Generated by Django 5.1.2 on 2025-09-29 13:14

import workbench.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0019_books_pdf_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSVoicePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tts_provider', models.CharField(choices=[('edge_tts', 'Edge TTS'), ('azure', 'Azure TTS')], max_length=20)),
                ('voice_name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, upload_to=workbench.models.tts_preview_upload_to)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tts_provider', 'voice_name'],
                'unique_together': {('tts_provider', 'voice_name')},
            },
        ),
    ]
