# Generated by Django 5.1.2 on 2025-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0020_ttsvoicepreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_provider', models.CharField(choices=[('edge_tts', 'Edge TTS'), ('azure', 'Azure TTS')], default='edge_tts', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TTS 供应商配置',
                'verbose_name_plural': 'TTS 供应商配置',
            },
        ),
    ]
