# Generated by Django 5.1.2 on 2025-10-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0022_inline_voice_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosegment',
            name='chapters',
            field=models.JSONField(blank=True, default=list, help_text='音频章节时间线'),
        ),
        migrations.AddField(
            model_name='dialoguescript',
            name='chapters',
            field=models.JSONField(blank=True, default=list, help_text='音频章节时间线'),
        ),
    ]
