# Generated by Django 5.1.2 on 2025-10-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0023_audiosegment_chapters_dialoguescript_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosegment',
            name='chapters_file',
            field=models.FileField(blank=True, null=True, upload_to='chapters/audio_segments/%Y/%m/%d/', verbose_name='章节JSON文件'),
        ),
        migrations.AddField(
            model_name='dialoguescript',
            name='chapters_file',
            field=models.FileField(blank=True, null=True, upload_to='chapters/dialogue_scripts/%Y/%m/%d/', verbose_name='章节JSON文件'),
        ),
    ]
