# Generated by Django 5.1.2 on 2025-10-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0024_audiosegment_chapters_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosegment',
            name='chapters_html',
            field=models.TextField(blank=True, default='', help_text='章节HTML片段'),
        ),
        migrations.AddField(
            model_name='dialoguescript',
            name='chapters_html',
            field=models.TextField(blank=True, default='', help_text='章节HTML片段'),
        ),
    ]
