# Generated by Django 5.1.2 on 2025-10-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0025_audiosegment_chapters_html_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_md5', models.CharField(db_index=True, help_text='原文本的MD5哈希值', max_length=32)),
                ('source_language', models.CharField(default='auto', help_text='源语言（auto表示自动检测）', max_length=10)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('zh', '中文'), ('ja', '日本語'), ('ko', '한국어'), ('fr', 'Français'), ('de', 'Deutsch'), ('es', 'Español'), ('ru', 'Русский'), ('it', 'Italiano'), ('pt', 'Português')], help_text='目标语言', max_length=10)),
                ('original_text', models.TextField(help_text='原始文本内容')),
                ('translated_text', models.TextField(help_text='翻译后的文本内容')),
                ('hit_count', models.IntegerField(default=1, help_text='缓存命中次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(auto_now_add=True, help_text='最后使用时间')),
            ],
            options={
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['text_md5', 'target_language'], name='workbench_t_text_md_652b78_idx'), models.Index(fields=['created_at'], name='workbench_t_created_c42d98_idx'), models.Index(fields=['last_used_at'], name='workbench_t_last_us_7c9c15_idx')],
                'unique_together': {('text_md5', 'target_language')},
            },
        ),
    ]
